import type { Metadata } from "next";
import "./globals.css";
import { myFont } from "./font";
import Footer from "@/components/footer";
import Header from "@/components/header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-bg text-text antialiased ${myFont.className}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
